"""
LLM module for the segmentation engine.

Contains LLM integration for actionability filtering and business translation.
"""

from src.llm.actionability_filter import (
    ActionabilityFilter,
    ActionabilityRule,
    LLMClient,
    MockLLMClient,
    evaluate_actionability,
    evaluate_actionability_rule_based,
    evaluate_actionability_with_llm,
    evaluate_how_dimension,
    evaluate_what_dimension,
    evaluate_when_dimension,
    evaluate_who_dimension,
    get_actionable_dimensions,
    get_default_rules,
    is_segment_actionable,
)
from src.llm.intent_templates import (
    PromptTemplate,
    PromptType,
    build_actionability_prompt,
    build_business_translation_prompt,
    build_campaign_recommendation_prompt,
    build_intent_interpretation_prompt,
    format_actionability_prompt,
    format_business_translation_prompt,
    format_campaign_recommendation_prompt,
    format_intent_interpretation_prompt,
    get_confidence_language,
    get_robustness_context,
    parse_json_response,
    validate_actionability_response,
    validate_business_translation_response,
)
from src.llm.segment_explainer import (
    SegmentExplainer,
    explain_segment,
    explain_segment_rule_based,
    explain_segment_with_llm,
    format_segment_for_presentation,
    generate_business_hypothesis,
    generate_executive_summary,
    generate_key_characteristics,
    generate_recommended_campaign,
    generate_roi_expectation,
    get_segment_recommendation,
    get_segment_summary,
)

__all__ = [
    # Actionability Filter
    "ActionabilityFilter",
    "ActionabilityRule",
    "LLMClient",
    "MockLLMClient",
    "evaluate_actionability",
    "evaluate_actionability_rule_based",
    "evaluate_actionability_with_llm",
    "evaluate_how_dimension",
    "evaluate_what_dimension",
    "evaluate_when_dimension",
    "evaluate_who_dimension",
    "get_actionable_dimensions",
    "get_default_rules",
    "is_segment_actionable",
    # Intent Templates
    "PromptTemplate",
    "PromptType",
    "build_actionability_prompt",
    "build_business_translation_prompt",
    "build_campaign_recommendation_prompt",
    "build_intent_interpretation_prompt",
    "format_actionability_prompt",
    "format_business_translation_prompt",
    "format_campaign_recommendation_prompt",
    "format_intent_interpretation_prompt",
    "get_confidence_language",
    "get_robustness_context",
    "parse_json_response",
    "validate_actionability_response",
    "validate_business_translation_response",
    # Segment Explainer
    "SegmentExplainer",
    "explain_segment",
    "explain_segment_rule_based",
    "explain_segment_with_llm",
    "format_segment_for_presentation",
    "generate_business_hypothesis",
    "generate_executive_summary",
    "generate_key_characteristics",
    "generate_recommended_campaign",
    "generate_roi_expectation",
    "get_segment_recommendation",
    "get_segment_summary",
]
